services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: .
    container_name: ngnix
    ports:
      - "80:80"
    networks:
      - inseption

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: .
    container_name: wordpress
    networks:
      - inseption

networks:
  inseption:
    driver:
      "bridge"